--Ingenieurs non affectés 
SELECT I.NOM, I.PRENOM, A.CODPRO
FROM INGENIEUR I LEFT OUTER JOIN AFFECT A 
ON I.MLE = A.MLE
WHERE CODPRO IS NULL;


--Test du all
SELECT *
FROM INGENIEUR
WHERE VILLE = ALL (SELECT VILLE FROM PROJET);


--